title: Hey It's Mariana Garcia Hernandez
description: > # this means to ignore newlines until "baseurl:"
  Mariana Garcia Software Engineer Profesional Blog
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "marianagh.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
imgrul: 'http://marianagh.github.io/assets/images/'

# Author Settings
author: Mariana Garcia Hernandez # add your name
author-img: mariana-garcia.jpg # add your photo
about-author: Enthusiastic, highly-motivated Software Engineer graduate with proven leadership capabilities. # add description
twitter: marianaghdev
facebook: # add your Facebook handle
github: marianagh
linkedin: in/marianagh
email: marianaghdev@gmail.com
# Disqus
discus-identifier: marianagh # add your discus identifier

# Tracker
analytics: UA-107007901-1

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

