--- 
background: assets/img/placeholder-big.jpg
bio: "Software Developer & Blogger"
description: "A blog to document my journey as a developer."
disqus_shortname: marianagh
exclude: 
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - gulpfile.js
  - package.json
  - _site
  - src
  - vendor
  - CNAME
  - LICENSE
  - Rakefile
gems: 
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
github-url: marianagh
highlighter: rouge
instagram: soymarianag
jekyll-mentions: 
  base_url: "https://github.com"
kramdown: 
  auto_ids: true
  enable_coderay: false
  entity_output: as_char
  footnote_nr: 1
  toc_levels: "1..6"
linkedin: in/marianagh
locale: en_US
logo: assets/img/mariana-garcia-hernandez-startup-weekend.jpg
markdown: kramdown
mathjax: true
permalink: "/:title/"
reading_time: true
sass: 
  sass_dir: _sass
  style: compressed
tiled_bg: false
title: "Mariana Garcia"
twitter: marianaghdev
url: "https://marianagh.github.io/"
words_per_minute: 200